Disallow empty feedbacks bug fixed
Memegle/memegle pull request #101
Opened 2021-01-10 08:25 UTC by Gin594

前端empty feedback改用state控制， 后端抛出http异常状态码+异常message.

2021-01-10 09:43 UTC, vinovo requested changes

2021-01-10 09:43 UTC, vinovo commented on client/src/routes/Result/index.js
> +                        { this.state.feedbackError && <p className={styles.error}>请输入反馈信息！</p>}
我觉得最好把error msg本身写在react state里面，参考result page本身的error那个state，因为除了空反馈还可能出现其他不同的feedback error。每一种error都分别建一个<p> tag应该没那么好。

2021-01-10 20:19 UTC, Gin594 commented
ok, 改了一下，从feedback.js文件里面接收后端的error，然后把error message放到feedback error的state中，tag p显示对应的error message。 你看一下，哪里还需要改跟我说。

2021-01-10 21:29 UTC, vinovo requested changes

2021-01-10 21:29 UTC, vinovo commented on client/src/routes/Result/index.js
> +                        {this.state.feedbackError && <p className={styles.error}>{this.state.feedbackError.message}</p>}
&& 前面的check可以不要了吧，如果feedbackError没有值那这个tag应该就不会显示了。

2021-01-10 21:29 UTC, vinovo commented on client/src/actions/feedback.js
> +    if (!response || response.status !== 200) {
后端返回的error要check。但是前端还是要加empty string的check，如果不符合要求的输入就不需要提交到后端了。这个check放在feedback.js里就行。

2021-01-10 22:17 UTC, Gin594 commented
已改

2021-01-11 00:51 UTC, vinovo approved these changes
well done!

2021-01-11 00:51 UTC, merged