revised baidu-scrapper
Memegle/memegle pull request #118
Opened 2021-03-06 12:54 UTC by FrankLi123

Revise the Baidu Scrapper

added arg parser revised command-line argument: python3 /scripts/baidu-scrapper.py -string (the keyword to be searched) - count (numbers of photos needed)

Stored all the meta data to meta.csv file.

The pictures were stored into MongoDB.

remaining bug:

if pictures are found already downloaded, the scrapper would have problem working.

2021-03-06 19:15 UTC, vinovo requested changes

2021-03-06 19:15 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +        filename = slugify(d['fromPageTitleEnc'], allow_unicode=True)
这里有两个点：
1. 现在已经没必要对本地的filename slugify了，因为我们到时会手动生成一个http friendly的ID，用作云端存储的key。所以不必调用slugify了。
2. 之前会碰到一个问题用d['fromPageTitleEnc']作为filename会有很多的同名文件，建议改动一下直接采用百度自己使用的文件名（通常应该是一串base64编码）。

2021-03-06 19:15 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +        writer.writerow({'source_url': img_url,'title':filename, 'path': path, 'source':query})
title这里可以继续采用d['fromPageTitleEnc']。同时百度爬下来的图片都是有tag的，也需要存储进meta.csv里，所以HEADERS这个变量名也要修改。

2021-03-06 19:15 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +tags = [query]
最好arg parser能支持用户添加额外的tags。

2021-03-06 19:15 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +CSV_PATH = 'data/raw/meta.csv'
这两行最好都调用一下abspath()这个方法来拿到绝对路径，因为到时migrate里使用绝对路径比较安全一些。

2021-03-06 19:31 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +for i in range(PHOTO_COUNT):
d['fromPageTitleEnc']

2021-03-07 23:40 UTC, FrankLi123 commented on server/scripts/baidu-scrapper.py
> +for i in range(PHOTO_COUNT):
是的 我的改动是设 END_PAGE 为int(PHOTO_COUNT / 30)+1 然后在loop中 把success和input count作比较 这样upper bound 就是最大页数

2021-03-07 23:51 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +for i in range(PHOTO_COUNT):
这个逻辑在现在的代码里有吗，在哪一行?我没看到ENG_PAGE这个变量被使用啊？

2021-05-15 09:42 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +    if isinstance(val,str) is fl:
这是啥意思，为啥不直接`if not isinstance(val, str):`

2021-05-17 20:07 UTC, vinovo requested changes
@FrankLi123 还有些小问题

2021-05-17 20:07 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +start_ind = page
这个也加个argument吧，默认值可以设成0，不然每次都从第一页开始下载会很多重复吧

2021-05-17 20:07 UTC, vinovo commented on server/scripts/baidu-scrapper.py
> +        writer.writerow({'source_url': img_url,'tag':TAGS,'title':d['fromPageTitleEnc'],'file_name':filename ,'path': path, 'source':QUERY,
source 改成`"baidu"`

2021-05-27 07:13 UTC, vinovo commented on server/scripts/baidu-scrapper.py
>  # The + sign force the result to include pattern 表情包
没用的comment删了吧

2021-08-09 20:08 UTC, closed without merging