dummy watermark prediction & integration
Memegle/memegle pull request #129
Opened 2021-06-19 17:32 UTC by minecx

see new lines in `migrate.py` & comments in `process_dir`

2021-06-21 19:56 UTC, vinovo commented on server/scripts/migrate.py
> +from server.scripts.watermark_predict_DUMMY import watermark_predict as wp
这里不明白，在那个文件里的方法不是叫`predict_watermark`吗，这里为什么import的是`watermark_predict`？

2021-06-21 19:58 UTC, vinovo requested changes

2021-06-21 19:58 UTC, vinovo commented on server/scripts/migrate.py
> +from server.scripts.watermark_predict_DUMMY import watermark_predict as wp
这里不明白，在那个文件里的方法不是叫`predict_watermark`吗，这里为什么import的是`watermark_predict`？

2021-06-21 19:58 UTC, vinovo commented on server/scripts/migrate.py
> +                    rename(path, join(watermark_dir, new_name))
用原文件名

2021-06-21 19:58 UTC, vinovo commented on server/scripts/migrate.py
> +from server.scripts.watermark_predict_DUMMY import watermark_predict as wp
另外这里不要用缩写吧，也不是什么有名的package，维护的人不知道wp是什么意思

2021-06-21 23:34 UTC, minecx commented on server/scripts/migrate.py
> +                    rename(path, join(watermark_dir, new_name))
这里不是要放到新的文件夹里面么？还是说`new_name` 应该写`filename`?

2021-06-21 23:59 UTC, vinovo commented on server/scripts/migrate.py
> +                    rename(path, join(watermark_dir, new_name))
用filename，写进了数据库的图片才用new_name。new_name是生成的uuid，用于访问图片的，没落库图片的没有这个需要

2021-06-22 00:01 UTC, minecx commented on server/scripts/migrate.py
> +                    rename(path, join(watermark_dir, new_name))
updated

2021-06-22 02:24 UTC, vinovo approved these changes
well done

2021-06-22 02:24 UTC, merged